from __future__ import annotations

from typing import Any


HONESTY_KEYWORDS = {
    "burger",
    "pizza",
    "fries",
    "shawarma",
    "chocolate",
    "cake",
    "ice cream",
    "beer",
    "wine",
    "cola",
    "soda",
}

GREEN_LIGHT_KEYWORDS = {
    "apple",
    "banana",
    "orange",
    "berry",
    "berries",
    "salad",
    "broccoli",
    "tomato",
    "cucumber",
    "carrot",
    "avocado",
    "fruit",
    "vegetable",
}

COFFEE_KEYWORDS = {
    "coffee",
    "espresso",
    "americano",
    "latte",
    "cappuccino",
    "raf",
    "flat white",
    "mocha",
    "кофе",
    "капучино",
    "латте",
    "раф",
    "американо",
}

ACHIEVEMENT_DEFINITIONS: list[dict[str, Any]] = [
    {
        "key": "first_bite",
        "title": "First Bite",
        "description": "Log your first meal",
        "metric": "total_meals",
        "target": 1,
    },
    {
        "key": "scanner_in_play",
        "title": "Scanner in Play",
        "description": "Confirm one AI meal",
        "metric": "ai_meals",
        "target": 1,
    },
    {
        "key": "manual_control",
        "title": "Manual Control",
        "description": "Add one meal manually",
        "metric": "manual_meals",
        "target": 1,
    },
    {
        "key": "precise_edit",
        "title": "Precise Edit",
        "description": "Recalculate one AI result before confirming",
        "metric": "scan_recalculations",
        "target": 1,
    },
    {
        "key": "sweet_truth",
        "title": "Sweet Truth",
        "description": "Log something indulgent without hiding it",
        "metric": "honesty_logs",
        "target": 1,
        "hidden": True,
    },
    {
        "key": "night_owl",
        "title": "Night Owl",
        "description": "Log a meal after 22:00",
        "metric": "late_night_logs",
        "target": 1,
        "hidden": True,
    },
    {
        "key": "green_light",
        "title": "Green Light",
        "description": "Log a fruit or vegetable",
        "metric": "green_logs",
        "target": 1,
    },
    {
        "key": "gourmet",
        "title": "Gourmet",
        "description": "Log 5 different foods in one day",
        "metric": "max_unique_items_day",
        "target": 5,
    },
    {
        "key": "morning_magic_bronze",
        "title": "Morning Magic",
        "description": "Log breakfast before 10:00",
        "metric": "breakfast_streak_days",
        "target": 1,
        "group": "morning_magic",
        "tier": "bronze",
    },
    {
        "key": "morning_magic_silver",
        "title": "Morning Magic",
        "description": "Log breakfast before 10:00 on 2 days in a row",
        "metric": "breakfast_streak_days",
        "target": 2,
        "group": "morning_magic",
        "tier": "silver",
    },
    {
        "key": "morning_magic_gold",
        "title": "Morning Magic",
        "description": "Log breakfast before 10:00 on 3 days in a row",
        "metric": "breakfast_streak_days",
        "target": 3,
        "group": "morning_magic",
        "tier": "gold",
    },
    {
        "key": "warm_streak_bronze",
        "title": "Warm Streak",
        "description": "Log meals 2 days in a row",
        "metric": "current_streak_days",
        "target": 2,
        "group": "warm_streak",
        "tier": "bronze",
    },
    {
        "key": "warm_streak_silver",
        "title": "Warm Streak",
        "description": "Log meals 4 days in a row",
        "metric": "current_streak_days",
        "target": 4,
        "group": "warm_streak",
        "tier": "silver",
    },
    {
        "key": "warm_streak_gold",
        "title": "Warm Streak",
        "description": "Log meals 7 days in a row",
        "metric": "current_streak_days",
        "target": 7,
        "group": "warm_streak",
        "tier": "gold",
    },
    {
        "key": "calorie_sniper",
        "title": "Calorie Sniper",
        "description": "Finish a day within 20 kcal of your goal",
        "metric": "calorie_sniper_days",
        "target": 1,
        "hidden": True,
    },
    {
        "key": "back_in_game",
        "title": "Back in the Game",
        "description": "Return after skipping at least one day",
        "metric": "comeback_days",
        "target": 1,
    },
    {
        "key": "weekend_hero",
        "title": "Weekend Hero",
        "description": "Log 2 meals on both Saturday and Sunday",
        "metric": "weekend_double_days",
        "target": 1,
    },
    {
        "key": "snack_master",
        "title": "Хрусть-хрусть",
        "description": "Log a snack or build a day with 4 or more meals",
        "metric": "snack_master_days",
        "target": 1,
    },
    {
        "key": "holy_trinity",
        "title": "Святая троица",
        "description": "Reach at least 75% of your protein, fat, and carbs goals in one day",
        "metric": "holy_trinity_days",
        "target": 1,
    },
    {
        "key": "meal_intervals",
        "title": "Интервалы",
        "description": "Log two meals 3 to 5 hours apart",
        "metric": "meal_interval_pairs",
        "target": 1,
    },
    {
        "key": "thursday_checkpoint",
        "title": "Экватор пройден",
        "description": "Log at least 2 meals on a Thursday",
        "metric": "thursday_two_meal_days",
        "target": 1,
    },
    {
        "key": "hat_trick",
        "title": "Хет-трик",
        "description": "Stay in the 85-115% calorie corridor for 3 days in a row",
        "metric": "calorie_corridor_streak_days",
        "target": 3,
    },
    {
        "key": "coffee_ninja",
        "title": "Кофеиновый ниндзя",
        "description": "Log coffee in any form",
        "metric": "coffee_logs",
        "target": 1,
    },
    {
        "key": "micro_control",
        "title": "Микро-контроль",
        "description": "Log something under 50 kcal",
        "metric": "micro_logs",
        "target": 1,
    },
    {
        "key": "big_feast",
        "title": "Пир на весь мир",
        "description": "Log one meal over 900 kcal",
        "metric": "big_feast_meals",
        "target": 1,
    },
]
